name: Build, Test and Publish Console App

on:
  workflow_call:
  workflow_dispatch:

env:
  SOLUTION_PATH: ./TestTag.sln
  PROJECT_PATH: ./TestTag.ConsoleApp/TestTag.ConsoleApp/TestTag.ConsoleApp.csproj
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: Release

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          

      - name: Setup .NET (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: |
            **/Directory.Packages.props
            **/*.csproj

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }} --no-build

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }} -o publish --no-build

      - name: Simulate Azure Deployment
        run: echo "Simulating publish to Azure"

      - name: Update last-deploy tag
        uses: hermitos/tag-deploy-actions/tag-push@v2.4
        with:
          tag: last-deploy-prod
